### ISSUE TITLE
consider exporting curl dependency

### ISSUE THREAD

**Issue by GlenDC** [LorenzoLeonardo/curl-http-client#23]
Eg export in ‘lib.rs’ as

```rust
pub mod dep {
    pub use curl;
}
```

I can add a PR for it.
It would mean that user will always be able to use that API layer without having to figure out compatible version.

It is also recommended in the API Rust Guidelines.

**Comment by GlenDC** [comment]
Motivation: types from that dependency are required for advanced use cases (eg custom ExtendedHandler)

**Comment by LorenzoLeonardo** [comment]
I appreciate such an update.  Thank you very much. I already published v0.3.0 of this crate

**Comment by LorenzoLeonardo** [comment]
I was motivated to create this crate because curl-rust only handles synchronous transactions. There are no crates that can perform curl-rust asynchronously. There are options that are not yet available with reqwest and curl is already mature enough to handle different HTTP transactions especially dealing with proxy.

**Comment by GlenDC** [comment]
Thanks for that and fully agree. That’s why I am contributing to your crates with pleasure. A small token of gratitude for all the effort you put into this. Thanks.
